version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./elekable_api
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    volumes:
      - ./elekable_api:/app
      - /app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development

  frontend:
    build: 
      context: ./elekable_webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./elekable_webapp:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mariadb_data:
  frontend_node_modules:
  frontend_next: